// PDFium-rs -- Modern Rust wrapper to PDFium, the PDF library from Google
//
// Copyright (c) 2025 Martin van der Werff <github (at) newinnovations.nl>
//
// This file is part of PDFium-rs.
//
// PDFium-rs is free software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software Foundation, either version 3
// of the License, or (at your option) any later version.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
// BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#![allow(clippy::too_many_arguments)]

use super::{Pdfium, PdfiumError, lib_get};
use libloading::Library;

impl Pdfium {
    pub fn new(lib: Library) -> Result<Self, PdfiumError> {
        Ok(Self {
            fn_FORM_CanRedo: *(lib_get(&lib, "FORM_CanRedo")?),
            fn_FORM_CanUndo: *(lib_get(&lib, "FORM_CanUndo")?),
            fn_FORM_DoDocumentAAction: *(lib_get(&lib, "FORM_DoDocumentAAction")?),
            fn_FORM_DoDocumentJSAction: *(lib_get(&lib, "FORM_DoDocumentJSAction")?),
            fn_FORM_DoDocumentOpenAction: *(lib_get(&lib, "FORM_DoDocumentOpenAction")?),
            fn_FORM_DoPageAAction: *(lib_get(&lib, "FORM_DoPageAAction")?),
            fn_FORM_ForceToKillFocus: *(lib_get(&lib, "FORM_ForceToKillFocus")?),
            fn_FORM_GetFocusedAnnot: *(lib_get(&lib, "FORM_GetFocusedAnnot")?),
            fn_FORM_GetFocusedText: *(lib_get(&lib, "FORM_GetFocusedText")?),
            fn_FORM_GetSelectedText: *(lib_get(&lib, "FORM_GetSelectedText")?),
            fn_FORM_IsIndexSelected: *(lib_get(&lib, "FORM_IsIndexSelected")?),
            fn_FORM_OnAfterLoadPage: *(lib_get(&lib, "FORM_OnAfterLoadPage")?),
            fn_FORM_OnBeforeClosePage: *(lib_get(&lib, "FORM_OnBeforeClosePage")?),
            fn_FORM_OnChar: *(lib_get(&lib, "FORM_OnChar")?),
            fn_FORM_OnFocus: *(lib_get(&lib, "FORM_OnFocus")?),
            fn_FORM_OnKeyDown: *(lib_get(&lib, "FORM_OnKeyDown")?),
            fn_FORM_OnKeyUp: *(lib_get(&lib, "FORM_OnKeyUp")?),
            fn_FORM_OnLButtonDoubleClick: *(lib_get(&lib, "FORM_OnLButtonDoubleClick")?),
            fn_FORM_OnLButtonDown: *(lib_get(&lib, "FORM_OnLButtonDown")?),
            fn_FORM_OnLButtonUp: *(lib_get(&lib, "FORM_OnLButtonUp")?),
            fn_FORM_OnMouseMove: *(lib_get(&lib, "FORM_OnMouseMove")?),
            fn_FORM_OnMouseWheel: *(lib_get(&lib, "FORM_OnMouseWheel")?),
            fn_FORM_OnRButtonDown: *(lib_get(&lib, "FORM_OnRButtonDown")?),
            fn_FORM_OnRButtonUp: *(lib_get(&lib, "FORM_OnRButtonUp")?),
            fn_FORM_Redo: *(lib_get(&lib, "FORM_Redo")?),
            fn_FORM_ReplaceAndKeepSelection: *(lib_get(&lib, "FORM_ReplaceAndKeepSelection")?),
            fn_FORM_ReplaceSelection: *(lib_get(&lib, "FORM_ReplaceSelection")?),
            fn_FORM_SelectAllText: *(lib_get(&lib, "FORM_SelectAllText")?),
            fn_FORM_SetFocusedAnnot: *(lib_get(&lib, "FORM_SetFocusedAnnot")?),
            fn_FORM_SetIndexSelected: *(lib_get(&lib, "FORM_SetIndexSelected")?),
            fn_FORM_Undo: *(lib_get(&lib, "FORM_Undo")?),
            fn_FPDFAction_GetDest: *(lib_get(&lib, "FPDFAction_GetDest")?),
            fn_FPDFAction_GetFilePath: *(lib_get(&lib, "FPDFAction_GetFilePath")?),
            fn_FPDFAction_GetType: *(lib_get(&lib, "FPDFAction_GetType")?),
            fn_FPDFAction_GetURIPath: *(lib_get(&lib, "FPDFAction_GetURIPath")?),
            fn_FPDFAnnot_AddFileAttachment: *(lib_get(&lib, "FPDFAnnot_AddFileAttachment")?),
            fn_FPDFAnnot_AddInkStroke: *(lib_get(&lib, "FPDFAnnot_AddInkStroke")?),
            fn_FPDFAnnot_AppendAttachmentPoints: *(lib_get(
                &lib,
                "FPDFAnnot_AppendAttachmentPoints",
            )?),
            fn_FPDFAnnot_AppendObject: *(lib_get(&lib, "FPDFAnnot_AppendObject")?),
            fn_FPDFAnnot_CountAttachmentPoints: *(lib_get(
                &lib,
                "FPDFAnnot_CountAttachmentPoints",
            )?),
            fn_FPDFAnnot_GetAP: *(lib_get(&lib, "FPDFAnnot_GetAP")?),
            fn_FPDFAnnot_GetAttachmentPoints: *(lib_get(&lib, "FPDFAnnot_GetAttachmentPoints")?),
            fn_FPDFAnnot_GetBorder: *(lib_get(&lib, "FPDFAnnot_GetBorder")?),
            fn_FPDFAnnot_GetColor: *(lib_get(&lib, "FPDFAnnot_GetColor")?),
            fn_FPDFAnnot_GetFileAttachment: *(lib_get(&lib, "FPDFAnnot_GetFileAttachment")?),
            fn_FPDFAnnot_GetFlags: *(lib_get(&lib, "FPDFAnnot_GetFlags")?),
            fn_FPDFAnnot_GetFocusableSubtypes: *(lib_get(&lib, "FPDFAnnot_GetFocusableSubtypes")?),
            fn_FPDFAnnot_GetFocusableSubtypesCount: *(lib_get(
                &lib,
                "FPDFAnnot_GetFocusableSubtypesCount",
            )?),
            fn_FPDFAnnot_GetFontColor: *(lib_get(&lib, "FPDFAnnot_GetFontColor")?),
            fn_FPDFAnnot_GetFontSize: *(lib_get(&lib, "FPDFAnnot_GetFontSize")?),
            fn_FPDFAnnot_GetFormAdditionalActionJavaScript: *(lib_get(
                &lib,
                "FPDFAnnot_GetFormAdditionalActionJavaScript",
            )?),
            fn_FPDFAnnot_GetFormControlCount: *(lib_get(&lib, "FPDFAnnot_GetFormControlCount")?),
            fn_FPDFAnnot_GetFormControlIndex: *(lib_get(&lib, "FPDFAnnot_GetFormControlIndex")?),
            fn_FPDFAnnot_GetFormFieldAlternateName: *(lib_get(
                &lib,
                "FPDFAnnot_GetFormFieldAlternateName",
            )?),
            fn_FPDFAnnot_GetFormFieldAtPoint: *(lib_get(&lib, "FPDFAnnot_GetFormFieldAtPoint")?),
            fn_FPDFAnnot_GetFormFieldExportValue: *(lib_get(
                &lib,
                "FPDFAnnot_GetFormFieldExportValue",
            )?),
            fn_FPDFAnnot_GetFormFieldFlags: *(lib_get(&lib, "FPDFAnnot_GetFormFieldFlags")?),
            fn_FPDFAnnot_GetFormFieldName: *(lib_get(&lib, "FPDFAnnot_GetFormFieldName")?),
            fn_FPDFAnnot_GetFormFieldType: *(lib_get(&lib, "FPDFAnnot_GetFormFieldType")?),
            fn_FPDFAnnot_GetFormFieldValue: *(lib_get(&lib, "FPDFAnnot_GetFormFieldValue")?),
            fn_FPDFAnnot_GetInkListCount: *(lib_get(&lib, "FPDFAnnot_GetInkListCount")?),
            fn_FPDFAnnot_GetInkListPath: *(lib_get(&lib, "FPDFAnnot_GetInkListPath")?),
            fn_FPDFAnnot_GetLine: *(lib_get(&lib, "FPDFAnnot_GetLine")?),
            fn_FPDFAnnot_GetLink: *(lib_get(&lib, "FPDFAnnot_GetLink")?),
            fn_FPDFAnnot_GetLinkedAnnot: *(lib_get(&lib, "FPDFAnnot_GetLinkedAnnot")?),
            fn_FPDFAnnot_GetNumberValue: *(lib_get(&lib, "FPDFAnnot_GetNumberValue")?),
            fn_FPDFAnnot_GetObject: *(lib_get(&lib, "FPDFAnnot_GetObject")?),
            fn_FPDFAnnot_GetObjectCount: *(lib_get(&lib, "FPDFAnnot_GetObjectCount")?),
            fn_FPDFAnnot_GetOptionCount: *(lib_get(&lib, "FPDFAnnot_GetOptionCount")?),
            fn_FPDFAnnot_GetOptionLabel: *(lib_get(&lib, "FPDFAnnot_GetOptionLabel")?),
            fn_FPDFAnnot_GetRect: *(lib_get(&lib, "FPDFAnnot_GetRect")?),
            fn_FPDFAnnot_GetStringValue: *(lib_get(&lib, "FPDFAnnot_GetStringValue")?),
            fn_FPDFAnnot_GetSubtype: *(lib_get(&lib, "FPDFAnnot_GetSubtype")?),
            fn_FPDFAnnot_GetValueType: *(lib_get(&lib, "FPDFAnnot_GetValueType")?),
            fn_FPDFAnnot_GetVertices: *(lib_get(&lib, "FPDFAnnot_GetVertices")?),
            fn_FPDFAnnot_HasAttachmentPoints: *(lib_get(&lib, "FPDFAnnot_HasAttachmentPoints")?),
            fn_FPDFAnnot_HasKey: *(lib_get(&lib, "FPDFAnnot_HasKey")?),
            fn_FPDFAnnot_IsChecked: *(lib_get(&lib, "FPDFAnnot_IsChecked")?),
            fn_FPDFAnnot_IsObjectSupportedSubtype: *(lib_get(
                &lib,
                "FPDFAnnot_IsObjectSupportedSubtype",
            )?),
            fn_FPDFAnnot_IsOptionSelected: *(lib_get(&lib, "FPDFAnnot_IsOptionSelected")?),
            fn_FPDFAnnot_IsSupportedSubtype: *(lib_get(&lib, "FPDFAnnot_IsSupportedSubtype")?),
            fn_FPDFAnnot_RemoveInkList: *(lib_get(&lib, "FPDFAnnot_RemoveInkList")?),
            fn_FPDFAnnot_RemoveObject: *(lib_get(&lib, "FPDFAnnot_RemoveObject")?),
            fn_FPDFAnnot_SetAP: *(lib_get(&lib, "FPDFAnnot_SetAP")?),
            fn_FPDFAnnot_SetAttachmentPoints: *(lib_get(&lib, "FPDFAnnot_SetAttachmentPoints")?),
            fn_FPDFAnnot_SetBorder: *(lib_get(&lib, "FPDFAnnot_SetBorder")?),
            fn_FPDFAnnot_SetColor: *(lib_get(&lib, "FPDFAnnot_SetColor")?),
            fn_FPDFAnnot_SetFlags: *(lib_get(&lib, "FPDFAnnot_SetFlags")?),
            fn_FPDFAnnot_SetFocusableSubtypes: *(lib_get(&lib, "FPDFAnnot_SetFocusableSubtypes")?),
            fn_FPDFAnnot_SetFontColor: *(lib_get(&lib, "FPDFAnnot_SetFontColor")?),
            fn_FPDFAnnot_SetFormFieldFlags: *(lib_get(&lib, "FPDFAnnot_SetFormFieldFlags")?),
            fn_FPDFAnnot_SetRect: *(lib_get(&lib, "FPDFAnnot_SetRect")?),
            fn_FPDFAnnot_SetStringValue: *(lib_get(&lib, "FPDFAnnot_SetStringValue")?),
            fn_FPDFAnnot_SetURI: *(lib_get(&lib, "FPDFAnnot_SetURI")?),
            fn_FPDFAnnot_UpdateObject: *(lib_get(&lib, "FPDFAnnot_UpdateObject")?),
            fn_FPDFAttachment_GetFile: *(lib_get(&lib, "FPDFAttachment_GetFile")?),
            fn_FPDFAttachment_GetName: *(lib_get(&lib, "FPDFAttachment_GetName")?),
            fn_FPDFAttachment_GetStringValue: *(lib_get(&lib, "FPDFAttachment_GetStringValue")?),
            fn_FPDFAttachment_GetSubtype: *(lib_get(&lib, "FPDFAttachment_GetSubtype")?),
            fn_FPDFAttachment_GetValueType: *(lib_get(&lib, "FPDFAttachment_GetValueType")?),
            fn_FPDFAttachment_HasKey: *(lib_get(&lib, "FPDFAttachment_HasKey")?),
            fn_FPDFAttachment_SetFile: *(lib_get(&lib, "FPDFAttachment_SetFile")?),
            fn_FPDFAttachment_SetStringValue: *(lib_get(&lib, "FPDFAttachment_SetStringValue")?),
            fn_FPDFAvail_Create: *(lib_get(&lib, "FPDFAvail_Create")?),
            fn_FPDFAvail_Destroy: *(lib_get(&lib, "FPDFAvail_Destroy")?),
            fn_FPDFAvail_GetDocument: *(lib_get(&lib, "FPDFAvail_GetDocument")?),
            fn_FPDFAvail_GetFirstPageNum: *(lib_get(&lib, "FPDFAvail_GetFirstPageNum")?),
            fn_FPDFAvail_IsDocAvail: *(lib_get(&lib, "FPDFAvail_IsDocAvail")?),
            fn_FPDFAvail_IsFormAvail: *(lib_get(&lib, "FPDFAvail_IsFormAvail")?),
            fn_FPDFAvail_IsLinearized: *(lib_get(&lib, "FPDFAvail_IsLinearized")?),
            fn_FPDFAvail_IsPageAvail: *(lib_get(&lib, "FPDFAvail_IsPageAvail")?),
            fn_FPDFBitmap_Create: *(lib_get(&lib, "FPDFBitmap_Create")?),
            fn_FPDFBitmap_CreateEx: *(lib_get(&lib, "FPDFBitmap_CreateEx")?),
            fn_FPDFBitmap_Destroy: *(lib_get(&lib, "FPDFBitmap_Destroy")?),
            fn_FPDFBitmap_FillRect: *(lib_get(&lib, "FPDFBitmap_FillRect")?),
            fn_FPDFBitmap_GetBuffer: *(lib_get(&lib, "FPDFBitmap_GetBuffer")?),
            fn_FPDFBitmap_GetFormat: *(lib_get(&lib, "FPDFBitmap_GetFormat")?),
            fn_FPDFBitmap_GetHeight: *(lib_get(&lib, "FPDFBitmap_GetHeight")?),
            fn_FPDFBitmap_GetStride: *(lib_get(&lib, "FPDFBitmap_GetStride")?),
            fn_FPDFBitmap_GetWidth: *(lib_get(&lib, "FPDFBitmap_GetWidth")?),
            fn_FPDFBookmark_Find: *(lib_get(&lib, "FPDFBookmark_Find")?),
            fn_FPDFBookmark_GetAction: *(lib_get(&lib, "FPDFBookmark_GetAction")?),
            fn_FPDFBookmark_GetCount: *(lib_get(&lib, "FPDFBookmark_GetCount")?),
            fn_FPDFBookmark_GetDest: *(lib_get(&lib, "FPDFBookmark_GetDest")?),
            fn_FPDFBookmark_GetFirstChild: *(lib_get(&lib, "FPDFBookmark_GetFirstChild")?),
            fn_FPDFBookmark_GetNextSibling: *(lib_get(&lib, "FPDFBookmark_GetNextSibling")?),
            fn_FPDFBookmark_GetTitle: *(lib_get(&lib, "FPDFBookmark_GetTitle")?),
            fn_FPDFCatalog_IsTagged: *(lib_get(&lib, "FPDFCatalog_IsTagged")?),
            fn_FPDFCatalog_SetLanguage: *(lib_get(&lib, "FPDFCatalog_SetLanguage")?),
            fn_FPDFClipPath_CountPathSegments: *(lib_get(&lib, "FPDFClipPath_CountPathSegments")?),
            fn_FPDFClipPath_CountPaths: *(lib_get(&lib, "FPDFClipPath_CountPaths")?),
            fn_FPDFClipPath_GetPathSegment: *(lib_get(&lib, "FPDFClipPath_GetPathSegment")?),
            fn_FPDFDOC_ExitFormFillEnvironment: *(lib_get(
                &lib,
                "FPDFDOC_ExitFormFillEnvironment",
            )?),
            fn_FPDFDOC_InitFormFillEnvironment: *(lib_get(
                &lib,
                "FPDFDOC_InitFormFillEnvironment",
            )?),
            fn_FPDFDest_GetDestPageIndex: *(lib_get(&lib, "FPDFDest_GetDestPageIndex")?),
            fn_FPDFDest_GetLocationInPage: *(lib_get(&lib, "FPDFDest_GetLocationInPage")?),
            fn_FPDFDest_GetView: *(lib_get(&lib, "FPDFDest_GetView")?),
            fn_FPDFDoc_AddAttachment: *(lib_get(&lib, "FPDFDoc_AddAttachment")?),
            fn_FPDFDoc_CloseJavaScriptAction: *(lib_get(&lib, "FPDFDoc_CloseJavaScriptAction")?),
            fn_FPDFDoc_DeleteAttachment: *(lib_get(&lib, "FPDFDoc_DeleteAttachment")?),
            fn_FPDFDoc_GetAttachment: *(lib_get(&lib, "FPDFDoc_GetAttachment")?),
            fn_FPDFDoc_GetAttachmentCount: *(lib_get(&lib, "FPDFDoc_GetAttachmentCount")?),
            fn_FPDFDoc_GetJavaScriptAction: *(lib_get(&lib, "FPDFDoc_GetJavaScriptAction")?),
            fn_FPDFDoc_GetJavaScriptActionCount: *(lib_get(
                &lib,
                "FPDFDoc_GetJavaScriptActionCount",
            )?),
            fn_FPDFDoc_GetPageMode: *(lib_get(&lib, "FPDFDoc_GetPageMode")?),
            fn_FPDFFont_Close: *(lib_get(&lib, "FPDFFont_Close")?),
            fn_FPDFFont_GetAscent: *(lib_get(&lib, "FPDFFont_GetAscent")?),
            fn_FPDFFont_GetBaseFontName: *(lib_get(&lib, "FPDFFont_GetBaseFontName")?),
            fn_FPDFFont_GetDescent: *(lib_get(&lib, "FPDFFont_GetDescent")?),
            fn_FPDFFont_GetFamilyName: *(lib_get(&lib, "FPDFFont_GetFamilyName")?),
            fn_FPDFFont_GetFlags: *(lib_get(&lib, "FPDFFont_GetFlags")?),
            fn_FPDFFont_GetFontData: *(lib_get(&lib, "FPDFFont_GetFontData")?),
            fn_FPDFFont_GetGlyphPath: *(lib_get(&lib, "FPDFFont_GetGlyphPath")?),
            fn_FPDFFont_GetGlyphWidth: *(lib_get(&lib, "FPDFFont_GetGlyphWidth")?),
            fn_FPDFFont_GetIsEmbedded: *(lib_get(&lib, "FPDFFont_GetIsEmbedded")?),
            fn_FPDFFont_GetItalicAngle: *(lib_get(&lib, "FPDFFont_GetItalicAngle")?),
            fn_FPDFFont_GetWeight: *(lib_get(&lib, "FPDFFont_GetWeight")?),
            fn_FPDFFormObj_CountObjects: *(lib_get(&lib, "FPDFFormObj_CountObjects")?),
            fn_FPDFFormObj_GetObject: *(lib_get(&lib, "FPDFFormObj_GetObject")?),
            fn_FPDFFormObj_RemoveObject: *(lib_get(&lib, "FPDFFormObj_RemoveObject")?),
            fn_FPDFGlyphPath_CountGlyphSegments: *(lib_get(
                &lib,
                "FPDFGlyphPath_CountGlyphSegments",
            )?),
            fn_FPDFGlyphPath_GetGlyphPathSegment: *(lib_get(
                &lib,
                "FPDFGlyphPath_GetGlyphPathSegment",
            )?),
            fn_FPDFImageObj_GetBitmap: *(lib_get(&lib, "FPDFImageObj_GetBitmap")?),
            fn_FPDFImageObj_GetIccProfileDataDecoded: *(lib_get(
                &lib,
                "FPDFImageObj_GetIccProfileDataDecoded",
            )?),
            fn_FPDFImageObj_GetImageDataDecoded: *(lib_get(
                &lib,
                "FPDFImageObj_GetImageDataDecoded",
            )?),
            fn_FPDFImageObj_GetImageDataRaw: *(lib_get(&lib, "FPDFImageObj_GetImageDataRaw")?),
            fn_FPDFImageObj_GetImageFilter: *(lib_get(&lib, "FPDFImageObj_GetImageFilter")?),
            fn_FPDFImageObj_GetImageFilterCount: *(lib_get(
                &lib,
                "FPDFImageObj_GetImageFilterCount",
            )?),
            fn_FPDFImageObj_GetImageMetadata: *(lib_get(&lib, "FPDFImageObj_GetImageMetadata")?),
            fn_FPDFImageObj_GetImagePixelSize: *(lib_get(&lib, "FPDFImageObj_GetImagePixelSize")?),
            fn_FPDFImageObj_GetRenderedBitmap: *(lib_get(&lib, "FPDFImageObj_GetRenderedBitmap")?),
            fn_FPDFImageObj_LoadJpegFile: *(lib_get(&lib, "FPDFImageObj_LoadJpegFile")?),
            fn_FPDFImageObj_LoadJpegFileInline: *(lib_get(
                &lib,
                "FPDFImageObj_LoadJpegFileInline",
            )?),
            fn_FPDFImageObj_SetBitmap: *(lib_get(&lib, "FPDFImageObj_SetBitmap")?),
            fn_FPDFImageObj_SetMatrix: *(lib_get(&lib, "FPDFImageObj_SetMatrix")?),
            fn_FPDFJavaScriptAction_GetName: *(lib_get(&lib, "FPDFJavaScriptAction_GetName")?),
            fn_FPDFJavaScriptAction_GetScript: *(lib_get(&lib, "FPDFJavaScriptAction_GetScript")?),
            fn_FPDFLink_CloseWebLinks: *(lib_get(&lib, "FPDFLink_CloseWebLinks")?),
            fn_FPDFLink_CountQuadPoints: *(lib_get(&lib, "FPDFLink_CountQuadPoints")?),
            fn_FPDFLink_CountRects: *(lib_get(&lib, "FPDFLink_CountRects")?),
            fn_FPDFLink_CountWebLinks: *(lib_get(&lib, "FPDFLink_CountWebLinks")?),
            fn_FPDFLink_Enumerate: *(lib_get(&lib, "FPDFLink_Enumerate")?),
            fn_FPDFLink_GetAction: *(lib_get(&lib, "FPDFLink_GetAction")?),
            fn_FPDFLink_GetAnnot: *(lib_get(&lib, "FPDFLink_GetAnnot")?),
            fn_FPDFLink_GetAnnotRect: *(lib_get(&lib, "FPDFLink_GetAnnotRect")?),
            fn_FPDFLink_GetDest: *(lib_get(&lib, "FPDFLink_GetDest")?),
            fn_FPDFLink_GetLinkAtPoint: *(lib_get(&lib, "FPDFLink_GetLinkAtPoint")?),
            fn_FPDFLink_GetLinkZOrderAtPoint: *(lib_get(&lib, "FPDFLink_GetLinkZOrderAtPoint")?),
            fn_FPDFLink_GetQuadPoints: *(lib_get(&lib, "FPDFLink_GetQuadPoints")?),
            fn_FPDFLink_GetRect: *(lib_get(&lib, "FPDFLink_GetRect")?),
            fn_FPDFLink_GetTextRange: *(lib_get(&lib, "FPDFLink_GetTextRange")?),
            fn_FPDFLink_GetURL: *(lib_get(&lib, "FPDFLink_GetURL")?),
            fn_FPDFLink_LoadWebLinks: *(lib_get(&lib, "FPDFLink_LoadWebLinks")?),
            fn_FPDFPageObjMark_CountParams: *(lib_get(&lib, "FPDFPageObjMark_CountParams")?),
            fn_FPDFPageObjMark_GetName: *(lib_get(&lib, "FPDFPageObjMark_GetName")?),
            fn_FPDFPageObjMark_GetParamBlobValue: *(lib_get(
                &lib,
                "FPDFPageObjMark_GetParamBlobValue",
            )?),
            fn_FPDFPageObjMark_GetParamIntValue: *(lib_get(
                &lib,
                "FPDFPageObjMark_GetParamIntValue",
            )?),
            fn_FPDFPageObjMark_GetParamKey: *(lib_get(&lib, "FPDFPageObjMark_GetParamKey")?),
            fn_FPDFPageObjMark_GetParamStringValue: *(lib_get(
                &lib,
                "FPDFPageObjMark_GetParamStringValue",
            )?),
            fn_FPDFPageObjMark_GetParamValueType: *(lib_get(
                &lib,
                "FPDFPageObjMark_GetParamValueType",
            )?),
            fn_FPDFPageObjMark_RemoveParam: *(lib_get(&lib, "FPDFPageObjMark_RemoveParam")?),
            fn_FPDFPageObjMark_SetBlobParam: *(lib_get(&lib, "FPDFPageObjMark_SetBlobParam")?),
            fn_FPDFPageObjMark_SetIntParam: *(lib_get(&lib, "FPDFPageObjMark_SetIntParam")?),
            fn_FPDFPageObjMark_SetStringParam: *(lib_get(&lib, "FPDFPageObjMark_SetStringParam")?),
            fn_FPDFPageObj_AddMark: *(lib_get(&lib, "FPDFPageObj_AddMark")?),
            fn_FPDFPageObj_CountMarks: *(lib_get(&lib, "FPDFPageObj_CountMarks")?),
            fn_FPDFPageObj_CreateNewPath: *(lib_get(&lib, "FPDFPageObj_CreateNewPath")?),
            fn_FPDFPageObj_CreateNewRect: *(lib_get(&lib, "FPDFPageObj_CreateNewRect")?),
            fn_FPDFPageObj_CreateTextObj: *(lib_get(&lib, "FPDFPageObj_CreateTextObj")?),
            fn_FPDFPageObj_Destroy: *(lib_get(&lib, "FPDFPageObj_Destroy")?),
            fn_FPDFPageObj_GetBounds: *(lib_get(&lib, "FPDFPageObj_GetBounds")?),
            fn_FPDFPageObj_GetClipPath: *(lib_get(&lib, "FPDFPageObj_GetClipPath")?),
            fn_FPDFPageObj_GetDashArray: *(lib_get(&lib, "FPDFPageObj_GetDashArray")?),
            fn_FPDFPageObj_GetDashCount: *(lib_get(&lib, "FPDFPageObj_GetDashCount")?),
            fn_FPDFPageObj_GetDashPhase: *(lib_get(&lib, "FPDFPageObj_GetDashPhase")?),
            fn_FPDFPageObj_GetFillColor: *(lib_get(&lib, "FPDFPageObj_GetFillColor")?),
            fn_FPDFPageObj_GetIsActive: *(lib_get(&lib, "FPDFPageObj_GetIsActive")?),
            fn_FPDFPageObj_GetLineCap: *(lib_get(&lib, "FPDFPageObj_GetLineCap")?),
            fn_FPDFPageObj_GetLineJoin: *(lib_get(&lib, "FPDFPageObj_GetLineJoin")?),
            fn_FPDFPageObj_GetMark: *(lib_get(&lib, "FPDFPageObj_GetMark")?),
            fn_FPDFPageObj_GetMarkedContentID: *(lib_get(&lib, "FPDFPageObj_GetMarkedContentID")?),
            fn_FPDFPageObj_GetMatrix: *(lib_get(&lib, "FPDFPageObj_GetMatrix")?),
            fn_FPDFPageObj_GetRotatedBounds: *(lib_get(&lib, "FPDFPageObj_GetRotatedBounds")?),
            fn_FPDFPageObj_GetStrokeColor: *(lib_get(&lib, "FPDFPageObj_GetStrokeColor")?),
            fn_FPDFPageObj_GetStrokeWidth: *(lib_get(&lib, "FPDFPageObj_GetStrokeWidth")?),
            fn_FPDFPageObj_GetType: *(lib_get(&lib, "FPDFPageObj_GetType")?),
            fn_FPDFPageObj_HasTransparency: *(lib_get(&lib, "FPDFPageObj_HasTransparency")?),
            fn_FPDFPageObj_NewImageObj: *(lib_get(&lib, "FPDFPageObj_NewImageObj")?),
            fn_FPDFPageObj_NewTextObj: *(lib_get(&lib, "FPDFPageObj_NewTextObj")?),
            fn_FPDFPageObj_RemoveMark: *(lib_get(&lib, "FPDFPageObj_RemoveMark")?),
            fn_FPDFPageObj_SetBlendMode: *(lib_get(&lib, "FPDFPageObj_SetBlendMode")?),
            fn_FPDFPageObj_SetDashArray: *(lib_get(&lib, "FPDFPageObj_SetDashArray")?),
            fn_FPDFPageObj_SetDashPhase: *(lib_get(&lib, "FPDFPageObj_SetDashPhase")?),
            fn_FPDFPageObj_SetFillColor: *(lib_get(&lib, "FPDFPageObj_SetFillColor")?),
            fn_FPDFPageObj_SetIsActive: *(lib_get(&lib, "FPDFPageObj_SetIsActive")?),
            fn_FPDFPageObj_SetLineCap: *(lib_get(&lib, "FPDFPageObj_SetLineCap")?),
            fn_FPDFPageObj_SetLineJoin: *(lib_get(&lib, "FPDFPageObj_SetLineJoin")?),
            fn_FPDFPageObj_SetMatrix: *(lib_get(&lib, "FPDFPageObj_SetMatrix")?),
            fn_FPDFPageObj_SetStrokeColor: *(lib_get(&lib, "FPDFPageObj_SetStrokeColor")?),
            fn_FPDFPageObj_SetStrokeWidth: *(lib_get(&lib, "FPDFPageObj_SetStrokeWidth")?),
            fn_FPDFPageObj_Transform: *(lib_get(&lib, "FPDFPageObj_Transform")?),
            fn_FPDFPageObj_TransformClipPath: *(lib_get(&lib, "FPDFPageObj_TransformClipPath")?),
            fn_FPDFPageObj_TransformF: *(lib_get(&lib, "FPDFPageObj_TransformF")?),
            fn_FPDFPage_CloseAnnot: *(lib_get(&lib, "FPDFPage_CloseAnnot")?),
            fn_FPDFPage_CountObjects: *(lib_get(&lib, "FPDFPage_CountObjects")?),
            fn_FPDFPage_CreateAnnot: *(lib_get(&lib, "FPDFPage_CreateAnnot")?),
            fn_FPDFPage_Delete: *(lib_get(&lib, "FPDFPage_Delete")?),
            fn_FPDFPage_Flatten: *(lib_get(&lib, "FPDFPage_Flatten")?),
            fn_FPDFPage_FormFieldZOrderAtPoint: *(lib_get(
                &lib,
                "FPDFPage_FormFieldZOrderAtPoint",
            )?),
            fn_FPDFPage_GenerateContent: *(lib_get(&lib, "FPDFPage_GenerateContent")?),
            fn_FPDFPage_GetAnnot: *(lib_get(&lib, "FPDFPage_GetAnnot")?),
            fn_FPDFPage_GetAnnotCount: *(lib_get(&lib, "FPDFPage_GetAnnotCount")?),
            fn_FPDFPage_GetAnnotIndex: *(lib_get(&lib, "FPDFPage_GetAnnotIndex")?),
            fn_FPDFPage_GetArtBox: *(lib_get(&lib, "FPDFPage_GetArtBox")?),
            fn_FPDFPage_GetBleedBox: *(lib_get(&lib, "FPDFPage_GetBleedBox")?),
            fn_FPDFPage_GetCropBox: *(lib_get(&lib, "FPDFPage_GetCropBox")?),
            fn_FPDFPage_GetDecodedThumbnailData: *(lib_get(
                &lib,
                "FPDFPage_GetDecodedThumbnailData",
            )?),
            fn_FPDFPage_GetMediaBox: *(lib_get(&lib, "FPDFPage_GetMediaBox")?),
            fn_FPDFPage_GetObject: *(lib_get(&lib, "FPDFPage_GetObject")?),
            fn_FPDFPage_GetRawThumbnailData: *(lib_get(&lib, "FPDFPage_GetRawThumbnailData")?),
            fn_FPDFPage_GetRotation: *(lib_get(&lib, "FPDFPage_GetRotation")?),
            fn_FPDFPage_GetThumbnailAsBitmap: *(lib_get(&lib, "FPDFPage_GetThumbnailAsBitmap")?),
            fn_FPDFPage_GetTrimBox: *(lib_get(&lib, "FPDFPage_GetTrimBox")?),
            fn_FPDFPage_HasFormFieldAtPoint: *(lib_get(&lib, "FPDFPage_HasFormFieldAtPoint")?),
            fn_FPDFPage_HasTransparency: *(lib_get(&lib, "FPDFPage_HasTransparency")?),
            fn_FPDFPage_InsertClipPath: *(lib_get(&lib, "FPDFPage_InsertClipPath")?),
            fn_FPDFPage_InsertObject: *(lib_get(&lib, "FPDFPage_InsertObject")?),
            fn_FPDFPage_InsertObjectAtIndex: *(lib_get(&lib, "FPDFPage_InsertObjectAtIndex")?),
            fn_FPDFPage_New: *(lib_get(&lib, "FPDFPage_New")?),
            fn_FPDFPage_RemoveAnnot: *(lib_get(&lib, "FPDFPage_RemoveAnnot")?),
            fn_FPDFPage_RemoveObject: *(lib_get(&lib, "FPDFPage_RemoveObject")?),
            fn_FPDFPage_SetArtBox: *(lib_get(&lib, "FPDFPage_SetArtBox")?),
            fn_FPDFPage_SetBleedBox: *(lib_get(&lib, "FPDFPage_SetBleedBox")?),
            fn_FPDFPage_SetCropBox: *(lib_get(&lib, "FPDFPage_SetCropBox")?),
            fn_FPDFPage_SetMediaBox: *(lib_get(&lib, "FPDFPage_SetMediaBox")?),
            fn_FPDFPage_SetRotation: *(lib_get(&lib, "FPDFPage_SetRotation")?),
            fn_FPDFPage_SetTrimBox: *(lib_get(&lib, "FPDFPage_SetTrimBox")?),
            fn_FPDFPage_TransFormWithClip: *(lib_get(&lib, "FPDFPage_TransFormWithClip")?),
            fn_FPDFPage_TransformAnnots: *(lib_get(&lib, "FPDFPage_TransformAnnots")?),
            fn_FPDFPathSegment_GetClose: *(lib_get(&lib, "FPDFPathSegment_GetClose")?),
            fn_FPDFPathSegment_GetPoint: *(lib_get(&lib, "FPDFPathSegment_GetPoint")?),
            fn_FPDFPathSegment_GetType: *(lib_get(&lib, "FPDFPathSegment_GetType")?),
            fn_FPDFPath_BezierTo: *(lib_get(&lib, "FPDFPath_BezierTo")?),
            fn_FPDFPath_Close: *(lib_get(&lib, "FPDFPath_Close")?),
            fn_FPDFPath_CountSegments: *(lib_get(&lib, "FPDFPath_CountSegments")?),
            fn_FPDFPath_GetDrawMode: *(lib_get(&lib, "FPDFPath_GetDrawMode")?),
            fn_FPDFPath_GetPathSegment: *(lib_get(&lib, "FPDFPath_GetPathSegment")?),
            fn_FPDFPath_LineTo: *(lib_get(&lib, "FPDFPath_LineTo")?),
            fn_FPDFPath_MoveTo: *(lib_get(&lib, "FPDFPath_MoveTo")?),
            fn_FPDFPath_SetDrawMode: *(lib_get(&lib, "FPDFPath_SetDrawMode")?),
            fn_FPDFSignatureObj_GetByteRange: *(lib_get(&lib, "FPDFSignatureObj_GetByteRange")?),
            fn_FPDFSignatureObj_GetContents: *(lib_get(&lib, "FPDFSignatureObj_GetContents")?),
            fn_FPDFSignatureObj_GetDocMDPPermission: *(lib_get(
                &lib,
                "FPDFSignatureObj_GetDocMDPPermission",
            )?),
            fn_FPDFSignatureObj_GetReason: *(lib_get(&lib, "FPDFSignatureObj_GetReason")?),
            fn_FPDFSignatureObj_GetSubFilter: *(lib_get(&lib, "FPDFSignatureObj_GetSubFilter")?),
            fn_FPDFSignatureObj_GetTime: *(lib_get(&lib, "FPDFSignatureObj_GetTime")?),
            fn_FPDFTextObj_GetFont: *(lib_get(&lib, "FPDFTextObj_GetFont")?),
            fn_FPDFTextObj_GetFontSize: *(lib_get(&lib, "FPDFTextObj_GetFontSize")?),
            fn_FPDFTextObj_GetRenderedBitmap: *(lib_get(&lib, "FPDFTextObj_GetRenderedBitmap")?),
            fn_FPDFTextObj_GetText: *(lib_get(&lib, "FPDFTextObj_GetText")?),
            fn_FPDFTextObj_GetTextRenderMode: *(lib_get(&lib, "FPDFTextObj_GetTextRenderMode")?),
            fn_FPDFTextObj_SetTextRenderMode: *(lib_get(&lib, "FPDFTextObj_SetTextRenderMode")?),
            fn_FPDFText_ClosePage: *(lib_get(&lib, "FPDFText_ClosePage")?),
            fn_FPDFText_CountChars: *(lib_get(&lib, "FPDFText_CountChars")?),
            fn_FPDFText_CountRects: *(lib_get(&lib, "FPDFText_CountRects")?),
            fn_FPDFText_FindClose: *(lib_get(&lib, "FPDFText_FindClose")?),
            fn_FPDFText_FindNext: *(lib_get(&lib, "FPDFText_FindNext")?),
            fn_FPDFText_FindPrev: *(lib_get(&lib, "FPDFText_FindPrev")?),
            fn_FPDFText_FindStart: *(lib_get(&lib, "FPDFText_FindStart")?),
            fn_FPDFText_GetBoundedText: *(lib_get(&lib, "FPDFText_GetBoundedText")?),
            fn_FPDFText_GetCharAngle: *(lib_get(&lib, "FPDFText_GetCharAngle")?),
            fn_FPDFText_GetCharBox: *(lib_get(&lib, "FPDFText_GetCharBox")?),
            fn_FPDFText_GetCharIndexAtPos: *(lib_get(&lib, "FPDFText_GetCharIndexAtPos")?),
            fn_FPDFText_GetCharIndexFromTextIndex: *(lib_get(
                &lib,
                "FPDFText_GetCharIndexFromTextIndex",
            )?),
            fn_FPDFText_GetCharOrigin: *(lib_get(&lib, "FPDFText_GetCharOrigin")?),
            fn_FPDFText_GetFillColor: *(lib_get(&lib, "FPDFText_GetFillColor")?),
            fn_FPDFText_GetFontInfo: *(lib_get(&lib, "FPDFText_GetFontInfo")?),
            fn_FPDFText_GetFontSize: *(lib_get(&lib, "FPDFText_GetFontSize")?),
            fn_FPDFText_GetFontWeight: *(lib_get(&lib, "FPDFText_GetFontWeight")?),
            fn_FPDFText_GetLooseCharBox: *(lib_get(&lib, "FPDFText_GetLooseCharBox")?),
            fn_FPDFText_GetMatrix: *(lib_get(&lib, "FPDFText_GetMatrix")?),
            fn_FPDFText_GetRect: *(lib_get(&lib, "FPDFText_GetRect")?),
            fn_FPDFText_GetSchCount: *(lib_get(&lib, "FPDFText_GetSchCount")?),
            fn_FPDFText_GetSchResultIndex: *(lib_get(&lib, "FPDFText_GetSchResultIndex")?),
            fn_FPDFText_GetStrokeColor: *(lib_get(&lib, "FPDFText_GetStrokeColor")?),
            fn_FPDFText_GetText: *(lib_get(&lib, "FPDFText_GetText")?),
            fn_FPDFText_GetTextIndexFromCharIndex: *(lib_get(
                &lib,
                "FPDFText_GetTextIndexFromCharIndex",
            )?),
            fn_FPDFText_GetTextObject: *(lib_get(&lib, "FPDFText_GetTextObject")?),
            fn_FPDFText_GetUnicode: *(lib_get(&lib, "FPDFText_GetUnicode")?),
            fn_FPDFText_HasUnicodeMapError: *(lib_get(&lib, "FPDFText_HasUnicodeMapError")?),
            fn_FPDFText_IsGenerated: *(lib_get(&lib, "FPDFText_IsGenerated")?),
            fn_FPDFText_IsHyphen: *(lib_get(&lib, "FPDFText_IsHyphen")?),
            fn_FPDFText_LoadCidType2Font: *(lib_get(&lib, "FPDFText_LoadCidType2Font")?),
            fn_FPDFText_LoadFont: *(lib_get(&lib, "FPDFText_LoadFont")?),
            fn_FPDFText_LoadPage: *(lib_get(&lib, "FPDFText_LoadPage")?),
            fn_FPDFText_LoadStandardFont: *(lib_get(&lib, "FPDFText_LoadStandardFont")?),
            fn_FPDFText_SetCharcodes: *(lib_get(&lib, "FPDFText_SetCharcodes")?),
            fn_FPDFText_SetText: *(lib_get(&lib, "FPDFText_SetText")?),
            fn_FPDF_AddInstalledFont: *(lib_get(&lib, "FPDF_AddInstalledFont")?),
            fn_FPDF_CloseDocument: *(lib_get(&lib, "FPDF_CloseDocument")?),
            fn_FPDF_ClosePage: *(lib_get(&lib, "FPDF_ClosePage")?),
            fn_FPDF_CloseXObject: *(lib_get(&lib, "FPDF_CloseXObject")?),
            fn_FPDF_CopyViewerPreferences: *(lib_get(&lib, "FPDF_CopyViewerPreferences")?),
            fn_FPDF_CountNamedDests: *(lib_get(&lib, "FPDF_CountNamedDests")?),
            fn_FPDF_CreateClipPath: *(lib_get(&lib, "FPDF_CreateClipPath")?),
            fn_FPDF_CreateNewDocument: *(lib_get(&lib, "FPDF_CreateNewDocument")?),
            fn_FPDF_DestroyClipPath: *(lib_get(&lib, "FPDF_DestroyClipPath")?),
            fn_FPDF_DestroyLibrary: *(lib_get(&lib, "FPDF_DestroyLibrary")?),
            fn_FPDF_DeviceToPage: *(lib_get(&lib, "FPDF_DeviceToPage")?),
            fn_FPDF_DocumentHasValidCrossReferenceTable: *(lib_get(
                &lib,
                "FPDF_DocumentHasValidCrossReferenceTable",
            )?),
            fn_FPDF_FFLDraw: *(lib_get(&lib, "FPDF_FFLDraw")?),
            fn_FPDF_FreeDefaultSystemFontInfo: *(lib_get(&lib, "FPDF_FreeDefaultSystemFontInfo")?),
            fn_FPDF_GetDefaultSystemFontInfo: *(lib_get(&lib, "FPDF_GetDefaultSystemFontInfo")?),
            fn_FPDF_GetDefaultTTFMap: *(lib_get(&lib, "FPDF_GetDefaultTTFMap")?),
            fn_FPDF_GetDefaultTTFMapCount: *(lib_get(&lib, "FPDF_GetDefaultTTFMapCount")?),
            fn_FPDF_GetDefaultTTFMapEntry: *(lib_get(&lib, "FPDF_GetDefaultTTFMapEntry")?),
            fn_FPDF_GetDocPermissions: *(lib_get(&lib, "FPDF_GetDocPermissions")?),
            fn_FPDF_GetDocUserPermissions: *(lib_get(&lib, "FPDF_GetDocUserPermissions")?),
            fn_FPDF_GetFileIdentifier: *(lib_get(&lib, "FPDF_GetFileIdentifier")?),
            fn_FPDF_GetFileVersion: *(lib_get(&lib, "FPDF_GetFileVersion")?),
            fn_FPDF_GetFormType: *(lib_get(&lib, "FPDF_GetFormType")?),
            fn_FPDF_GetLastError: *(lib_get(&lib, "FPDF_GetLastError")?),
            fn_FPDF_GetMetaText: *(lib_get(&lib, "FPDF_GetMetaText")?),
            fn_FPDF_GetNamedDest: *(lib_get(&lib, "FPDF_GetNamedDest")?),
            fn_FPDF_GetNamedDestByName: *(lib_get(&lib, "FPDF_GetNamedDestByName")?),
            fn_FPDF_GetPageAAction: *(lib_get(&lib, "FPDF_GetPageAAction")?),
            fn_FPDF_GetPageBoundingBox: *(lib_get(&lib, "FPDF_GetPageBoundingBox")?),
            fn_FPDF_GetPageCount: *(lib_get(&lib, "FPDF_GetPageCount")?),
            fn_FPDF_GetPageHeight: *(lib_get(&lib, "FPDF_GetPageHeight")?),
            fn_FPDF_GetPageHeightF: *(lib_get(&lib, "FPDF_GetPageHeightF")?),
            fn_FPDF_GetPageLabel: *(lib_get(&lib, "FPDF_GetPageLabel")?),
            fn_FPDF_GetPageSizeByIndex: *(lib_get(&lib, "FPDF_GetPageSizeByIndex")?),
            fn_FPDF_GetPageSizeByIndexF: *(lib_get(&lib, "FPDF_GetPageSizeByIndexF")?),
            fn_FPDF_GetPageWidth: *(lib_get(&lib, "FPDF_GetPageWidth")?),
            fn_FPDF_GetPageWidthF: *(lib_get(&lib, "FPDF_GetPageWidthF")?),
            fn_FPDF_GetSecurityHandlerRevision: *(lib_get(
                &lib,
                "FPDF_GetSecurityHandlerRevision",
            )?),
            fn_FPDF_GetSignatureCount: *(lib_get(&lib, "FPDF_GetSignatureCount")?),
            fn_FPDF_GetSignatureObject: *(lib_get(&lib, "FPDF_GetSignatureObject")?),
            fn_FPDF_GetTrailerEnds: *(lib_get(&lib, "FPDF_GetTrailerEnds")?),
            fn_FPDF_GetXFAPacketContent: *(lib_get(&lib, "FPDF_GetXFAPacketContent")?),
            fn_FPDF_GetXFAPacketCount: *(lib_get(&lib, "FPDF_GetXFAPacketCount")?),
            fn_FPDF_GetXFAPacketName: *(lib_get(&lib, "FPDF_GetXFAPacketName")?),
            fn_FPDF_ImportNPagesToOne: *(lib_get(&lib, "FPDF_ImportNPagesToOne")?),
            fn_FPDF_ImportPages: *(lib_get(&lib, "FPDF_ImportPages")?),
            fn_FPDF_ImportPagesByIndex: *(lib_get(&lib, "FPDF_ImportPagesByIndex")?),
            fn_FPDF_InitLibrary: *(lib_get(&lib, "FPDF_InitLibrary")?),
            fn_FPDF_InitLibraryWithConfig: *(lib_get(&lib, "FPDF_InitLibraryWithConfig")?),
            fn_FPDF_LoadCustomDocument: *(lib_get(&lib, "FPDF_LoadCustomDocument")?),
            fn_FPDF_LoadPage: *(lib_get(&lib, "FPDF_LoadPage")?),
            fn_FPDF_LoadXFA: *(lib_get(&lib, "FPDF_LoadXFA")?),
            fn_FPDF_MovePages: *(lib_get(&lib, "FPDF_MovePages")?),
            fn_FPDF_NewFormObjectFromXObject: *(lib_get(&lib, "FPDF_NewFormObjectFromXObject")?),
            fn_FPDF_NewXObjectFromPage: *(lib_get(&lib, "FPDF_NewXObjectFromPage")?),
            fn_FPDF_PageToDevice: *(lib_get(&lib, "FPDF_PageToDevice")?),
            fn_FPDF_RemoveFormFieldHighlight: *(lib_get(&lib, "FPDF_RemoveFormFieldHighlight")?),
            fn_FPDF_RenderPageBitmap: *(lib_get(&lib, "FPDF_RenderPageBitmap")?),
            fn_FPDF_RenderPageBitmapWithColorScheme_Start: *(lib_get(
                &lib,
                "FPDF_RenderPageBitmapWithColorScheme_Start",
            )?),
            fn_FPDF_RenderPageBitmapWithMatrix: *(lib_get(
                &lib,
                "FPDF_RenderPageBitmapWithMatrix",
            )?),
            fn_FPDF_RenderPageBitmap_Start: *(lib_get(&lib, "FPDF_RenderPageBitmap_Start")?),
            fn_FPDF_RenderPage_Close: *(lib_get(&lib, "FPDF_RenderPage_Close")?),
            fn_FPDF_RenderPage_Continue: *(lib_get(&lib, "FPDF_RenderPage_Continue")?),
            fn_FPDF_SaveAsCopy: *(lib_get(&lib, "FPDF_SaveAsCopy")?),
            fn_FPDF_SaveWithVersion: *(lib_get(&lib, "FPDF_SaveWithVersion")?),
            fn_FPDF_SetFormFieldHighlightAlpha: *(lib_get(
                &lib,
                "FPDF_SetFormFieldHighlightAlpha",
            )?),
            fn_FPDF_SetFormFieldHighlightColor: *(lib_get(
                &lib,
                "FPDF_SetFormFieldHighlightColor",
            )?),
            fn_FPDF_SetSandBoxPolicy: *(lib_get(&lib, "FPDF_SetSandBoxPolicy")?),
            fn_FPDF_SetSystemFontInfo: *(lib_get(&lib, "FPDF_SetSystemFontInfo")?),
            fn_FPDF_StructElement_Attr_CountChildren: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_CountChildren",
            )?),
            fn_FPDF_StructElement_Attr_GetBlobValue: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetBlobValue",
            )?),
            fn_FPDF_StructElement_Attr_GetBooleanValue: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetBooleanValue",
            )?),
            fn_FPDF_StructElement_Attr_GetChildAtIndex: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetChildAtIndex",
            )?),
            fn_FPDF_StructElement_Attr_GetCount: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetCount",
            )?),
            fn_FPDF_StructElement_Attr_GetName: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetName",
            )?),
            fn_FPDF_StructElement_Attr_GetNumberValue: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetNumberValue",
            )?),
            fn_FPDF_StructElement_Attr_GetStringValue: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetStringValue",
            )?),
            fn_FPDF_StructElement_Attr_GetType: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetType",
            )?),
            fn_FPDF_StructElement_Attr_GetValue: *(lib_get(
                &lib,
                "FPDF_StructElement_Attr_GetValue",
            )?),
            fn_FPDF_StructElement_CountChildren: *(lib_get(
                &lib,
                "FPDF_StructElement_CountChildren",
            )?),
            fn_FPDF_StructElement_GetActualText: *(lib_get(
                &lib,
                "FPDF_StructElement_GetActualText",
            )?),
            fn_FPDF_StructElement_GetAltText: *(lib_get(&lib, "FPDF_StructElement_GetAltText")?),
            fn_FPDF_StructElement_GetAttributeAtIndex: *(lib_get(
                &lib,
                "FPDF_StructElement_GetAttributeAtIndex",
            )?),
            fn_FPDF_StructElement_GetAttributeCount: *(lib_get(
                &lib,
                "FPDF_StructElement_GetAttributeCount",
            )?),
            fn_FPDF_StructElement_GetChildAtIndex: *(lib_get(
                &lib,
                "FPDF_StructElement_GetChildAtIndex",
            )?),
            fn_FPDF_StructElement_GetChildMarkedContentID: *(lib_get(
                &lib,
                "FPDF_StructElement_GetChildMarkedContentID",
            )?),
            fn_FPDF_StructElement_GetID: *(lib_get(&lib, "FPDF_StructElement_GetID")?),
            fn_FPDF_StructElement_GetLang: *(lib_get(&lib, "FPDF_StructElement_GetLang")?),
            fn_FPDF_StructElement_GetMarkedContentID: *(lib_get(
                &lib,
                "FPDF_StructElement_GetMarkedContentID",
            )?),
            fn_FPDF_StructElement_GetMarkedContentIdAtIndex: *(lib_get(
                &lib,
                "FPDF_StructElement_GetMarkedContentIdAtIndex",
            )?),
            fn_FPDF_StructElement_GetMarkedContentIdCount: *(lib_get(
                &lib,
                "FPDF_StructElement_GetMarkedContentIdCount",
            )?),
            fn_FPDF_StructElement_GetObjType: *(lib_get(&lib, "FPDF_StructElement_GetObjType")?),
            fn_FPDF_StructElement_GetParent: *(lib_get(&lib, "FPDF_StructElement_GetParent")?),
            fn_FPDF_StructElement_GetStringAttribute: *(lib_get(
                &lib,
                "FPDF_StructElement_GetStringAttribute",
            )?),
            fn_FPDF_StructElement_GetTitle: *(lib_get(&lib, "FPDF_StructElement_GetTitle")?),
            fn_FPDF_StructElement_GetType: *(lib_get(&lib, "FPDF_StructElement_GetType")?),
            fn_FPDF_StructTree_Close: *(lib_get(&lib, "FPDF_StructTree_Close")?),
            fn_FPDF_StructTree_CountChildren: *(lib_get(&lib, "FPDF_StructTree_CountChildren")?),
            fn_FPDF_StructTree_GetChildAtIndex: *(lib_get(
                &lib,
                "FPDF_StructTree_GetChildAtIndex",
            )?),
            fn_FPDF_StructTree_GetForPage: *(lib_get(&lib, "FPDF_StructTree_GetForPage")?),
            fn_FPDF_VIEWERREF_GetDuplex: *(lib_get(&lib, "FPDF_VIEWERREF_GetDuplex")?),
            fn_FPDF_VIEWERREF_GetName: *(lib_get(&lib, "FPDF_VIEWERREF_GetName")?),
            fn_FPDF_VIEWERREF_GetNumCopies: *(lib_get(&lib, "FPDF_VIEWERREF_GetNumCopies")?),
            fn_FPDF_VIEWERREF_GetPrintPageRange: *(lib_get(
                &lib,
                "FPDF_VIEWERREF_GetPrintPageRange",
            )?),
            fn_FPDF_VIEWERREF_GetPrintPageRangeCount: *(lib_get(
                &lib,
                "FPDF_VIEWERREF_GetPrintPageRangeCount",
            )?),
            fn_FPDF_VIEWERREF_GetPrintPageRangeElement: *(lib_get(
                &lib,
                "FPDF_VIEWERREF_GetPrintPageRangeElement",
            )?),
            fn_FPDF_VIEWERREF_GetPrintScaling: *(lib_get(&lib, "FPDF_VIEWERREF_GetPrintScaling")?),
            fn_FSDK_SetUnSpObjProcessHandler: *(lib_get(&lib, "FSDK_SetUnSpObjProcessHandler")?),
            _lib: lib,
        })
    }
}
