// PDFium-rs -- Modern Rust interface to PDFium, the PDF library from Google
//
// Copyright (c) 2025 Martin van der Werff <github (at) newinnovations.nl>
//
// This file is part of PDFium-rs.
//
// PDFium-rs is free software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software Foundation, either version 3
// of the License, or (at your option) any later version.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
// BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#![allow(non_upper_case_globals)]
#![allow(dead_code)]

//! Constants used by the PDFium C library

use crate::pdfium_types::*;

pub const FALSE: i32 = 0;

pub const FPDF_OBJECT_UNKNOWN: i32 = 0;
pub const FPDF_OBJECT_BOOLEAN: i32 = 1;
pub const FPDF_OBJECT_NUMBER: i32 = 2;
pub const FPDF_OBJECT_STRING: i32 = 3;
pub const FPDF_OBJECT_NAME: i32 = 4;
pub const FPDF_OBJECT_ARRAY: i32 = 5;
pub const FPDF_OBJECT_DICTIONARY: i32 = 6;
pub const FPDF_OBJECT_STREAM: i32 = 7;
pub const FPDF_OBJECT_NULLOBJ: i32 = 8;
pub const FPDF_OBJECT_REFERENCE: i32 = 9;
pub const FPDF_POLICY_MACHINETIME_ACCESS: i32 = 0;
pub const FPDF_ERR_SUCCESS: i32 = 0;
pub const FPDF_ERR_UNKNOWN: i32 = 1;
pub const FPDF_ERR_FILE: i32 = 2;
pub const FPDF_ERR_FORMAT: i32 = 3;
pub const FPDF_ERR_PASSWORD: i32 = 4;
pub const FPDF_ERR_SECURITY: i32 = 5;
pub const FPDF_ERR_PAGE: i32 = 6;
pub const FPDF_ANNOT: i32 = 1;
pub const FPDF_LCD_TEXT: i32 = 2;
pub const FPDF_NO_NATIVETEXT: i32 = 4;
pub const FPDF_GRAYSCALE: i32 = 8;
pub const FPDF_DEBUG_INFO: i32 = 128;
pub const FPDF_NO_CATCH: i32 = 256;
pub const FPDF_RENDER_LIMITEDIMAGECACHE: i32 = 512;
pub const FPDF_RENDER_FORCEHALFTONE: i32 = 1024;
pub const FPDF_PRINTING: i32 = 2048;
pub const FPDF_RENDER_NO_SMOOTHTEXT: i32 = 4096;
pub const FPDF_RENDER_NO_SMOOTHIMAGE: i32 = 8192;
pub const FPDF_RENDER_NO_SMOOTHPATH: i32 = 16384;
pub const FPDF_REVERSE_BYTE_ORDER: i32 = 16;
pub const FPDF_CONVERT_FILL_TO_STROKE: i32 = 32;
pub const FPDFBitmap_Unknown: i32 = 0;
pub const FPDFBitmap_Gray: i32 = 1;
pub const FPDFBitmap_BGR: i32 = 2;
pub const FPDFBitmap_BGRx: i32 = 3;
pub const FPDFBitmap_BGRA: i32 = 4;
pub const FPDFBitmap_BGRA_Premul: i32 = 5;
pub const FPDFDOC_AACTION_WC: i32 = 16;
pub const FPDFDOC_AACTION_WS: i32 = 17;
pub const FPDFDOC_AACTION_DS: i32 = 18;
pub const FPDFDOC_AACTION_WP: i32 = 19;
pub const FPDFDOC_AACTION_DP: i32 = 20;
pub const FPDFPAGE_AACTION_OPEN: i32 = 0;
pub const FPDFPAGE_AACTION_CLOSE: i32 = 1;
pub const FPDF_FORMFIELD_UNKNOWN: i32 = 0;
pub const FPDF_FORMFIELD_PUSHBUTTON: i32 = 1;
pub const FPDF_FORMFIELD_CHECKBOX: i32 = 2;
pub const FPDF_FORMFIELD_RADIOBUTTON: i32 = 3;
pub const FPDF_FORMFIELD_COMBOBOX: i32 = 4;
pub const FPDF_FORMFIELD_LISTBOX: i32 = 5;
pub const FPDF_FORMFIELD_TEXTFIELD: i32 = 6;
pub const FPDF_FORMFIELD_SIGNATURE: i32 = 7;
pub const FPDF_FORMFIELD_COUNT: i32 = 8;
pub const FPDF_ANNOT_UNKNOWN: i32 = 0;
pub const FPDF_ANNOT_TEXT: i32 = 1;
pub const FPDF_ANNOT_LINK: i32 = 2;
pub const FPDF_ANNOT_FREETEXT: i32 = 3;
pub const FPDF_ANNOT_LINE: i32 = 4;
pub const FPDF_ANNOT_SQUARE: i32 = 5;
pub const FPDF_ANNOT_CIRCLE: i32 = 6;
pub const FPDF_ANNOT_POLYGON: i32 = 7;
pub const FPDF_ANNOT_POLYLINE: i32 = 8;
pub const FPDF_ANNOT_HIGHLIGHT: i32 = 9;
pub const FPDF_ANNOT_UNDERLINE: i32 = 10;
pub const FPDF_ANNOT_SQUIGGLY: i32 = 11;
pub const FPDF_ANNOT_STRIKEOUT: i32 = 12;
pub const FPDF_ANNOT_STAMP: i32 = 13;
pub const FPDF_ANNOT_CARET: i32 = 14;
pub const FPDF_ANNOT_INK: i32 = 15;
pub const FPDF_ANNOT_POPUP: i32 = 16;
pub const FPDF_ANNOT_FILEATTACHMENT: i32 = 17;
pub const FPDF_ANNOT_SOUND: i32 = 18;
pub const FPDF_ANNOT_MOVIE: i32 = 19;
pub const FPDF_ANNOT_WIDGET: i32 = 20;
pub const FPDF_ANNOT_SCREEN: i32 = 21;
pub const FPDF_ANNOT_PRINTERMARK: i32 = 22;
pub const FPDF_ANNOT_TRAPNET: i32 = 23;
pub const FPDF_ANNOT_WATERMARK: i32 = 24;
pub const FPDF_ANNOT_THREED: i32 = 25;
pub const FPDF_ANNOT_RICHMEDIA: i32 = 26;
pub const FPDF_ANNOT_XFAWIDGET: i32 = 27;
pub const FPDF_ANNOT_REDACT: i32 = 28;
pub const FPDF_ANNOT_FLAG_NONE: i32 = 0;
pub const FPDF_ANNOT_FLAG_INVISIBLE: i32 = 1;
pub const FPDF_ANNOT_FLAG_HIDDEN: i32 = 2;
pub const FPDF_ANNOT_FLAG_PRINT: i32 = 4;
pub const FPDF_ANNOT_FLAG_NOZOOM: i32 = 8;
pub const FPDF_ANNOT_FLAG_NOROTATE: i32 = 16;
pub const FPDF_ANNOT_FLAG_NOVIEW: i32 = 32;
pub const FPDF_ANNOT_FLAG_READONLY: i32 = 64;
pub const FPDF_ANNOT_FLAG_LOCKED: i32 = 128;
pub const FPDF_ANNOT_FLAG_TOGGLENOVIEW: i32 = 256;
pub const FPDF_ANNOT_APPEARANCEMODE_NORMAL: i32 = 0;
pub const FPDF_ANNOT_APPEARANCEMODE_ROLLOVER: i32 = 1;
pub const FPDF_ANNOT_APPEARANCEMODE_DOWN: i32 = 2;
pub const FPDF_ANNOT_APPEARANCEMODE_COUNT: i32 = 3;
pub const FPDF_FORMFLAG_NONE: i32 = 0;
pub const FPDF_FORMFLAG_READONLY: i32 = 1;
pub const FPDF_FORMFLAG_REQUIRED: i32 = 2;
pub const FPDF_FORMFLAG_NOEXPORT: i32 = 4;
pub const FPDF_FORMFLAG_TEXT_MULTILINE: i32 = 4096;
pub const FPDF_FORMFLAG_TEXT_PASSWORD: i32 = 8192;
pub const FPDF_FORMFLAG_CHOICE_COMBO: i32 = 131072;
pub const FPDF_FORMFLAG_CHOICE_EDIT: i32 = 262144;
pub const FPDF_FORMFLAG_CHOICE_MULTI_SELECT: i32 = 2097152;
pub const FPDF_ANNOT_AACTION_KEY_STROKE: i32 = 12;
pub const FPDF_ANNOT_AACTION_FORMAT: i32 = 13;
pub const FPDF_ANNOT_AACTION_VALIDATE: i32 = 14;
pub const FPDF_ANNOT_AACTION_CALCULATE: i32 = 15;
pub const FPDF_COLORSPACE_UNKNOWN: i32 = 0;
pub const FPDF_COLORSPACE_DEVICEGRAY: i32 = 1;
pub const FPDF_COLORSPACE_DEVICERGB: i32 = 2;
pub const FPDF_COLORSPACE_DEVICECMYK: i32 = 3;
pub const FPDF_COLORSPACE_CALGRAY: i32 = 4;
pub const FPDF_COLORSPACE_CALRGB: i32 = 5;
pub const FPDF_COLORSPACE_LAB: i32 = 6;
pub const FPDF_COLORSPACE_ICCBASED: i32 = 7;
pub const FPDF_COLORSPACE_SEPARATION: i32 = 8;
pub const FPDF_COLORSPACE_DEVICEN: i32 = 9;
pub const FPDF_COLORSPACE_INDEXED: i32 = 10;
pub const FPDF_COLORSPACE_PATTERN: i32 = 11;
pub const FPDF_PAGEOBJ_UNKNOWN: i32 = 0;
pub const FPDF_PAGEOBJ_TEXT: i32 = 1;
pub const FPDF_PAGEOBJ_PATH: i32 = 2;
pub const FPDF_PAGEOBJ_IMAGE: i32 = 3;
pub const FPDF_PAGEOBJ_SHADING: i32 = 4;
pub const FPDF_PAGEOBJ_FORM: i32 = 5;
pub const FPDF_SEGMENT_UNKNOWN: i32 = -1;
pub const FPDF_SEGMENT_LINETO: i32 = 0;
pub const FPDF_SEGMENT_BEZIERTO: i32 = 1;
pub const FPDF_SEGMENT_MOVETO: i32 = 2;
pub const FPDF_FILLMODE_NONE: i32 = 0;
pub const FPDF_FILLMODE_ALTERNATE: i32 = 1;
pub const FPDF_FILLMODE_WINDING: i32 = 2;
pub const FPDF_FONT_TYPE1: i32 = 1;
pub const FPDF_FONT_TRUETYPE: i32 = 2;
pub const FPDF_LINECAP_BUTT: i32 = 0;
pub const FPDF_LINECAP_ROUND: i32 = 1;
pub const FPDF_LINECAP_PROJECTING_SQUARE: i32 = 2;
pub const FPDF_LINEJOIN_MITER: i32 = 0;
pub const FPDF_LINEJOIN_ROUND: i32 = 1;
pub const FPDF_LINEJOIN_BEVEL: i32 = 2;
pub const FPDF_PRINTMODE_EMF: i32 = 0;
pub const FPDF_PRINTMODE_TEXTONLY: i32 = 1;
pub const FPDF_PRINTMODE_POSTSCRIPT2: i32 = 2;
pub const FPDF_PRINTMODE_POSTSCRIPT3: i32 = 3;
pub const FPDF_PRINTMODE_POSTSCRIPT2_PASSTHROUGH: i32 = 4;
pub const FPDF_PRINTMODE_POSTSCRIPT3_PASSTHROUGH: i32 = 5;
pub const FPDF_PRINTMODE_EMF_IMAGE_MASKS: i32 = 6;
pub const FPDF_PRINTMODE_POSTSCRIPT3_TYPE42: i32 = 7;
pub const FPDF_PRINTMODE_POSTSCRIPT3_TYPE42_PASSTHROUGH: i32 = 8;
pub const FPDF_UNSP_DOC_XFAFORM: i32 = 1;
pub const FPDF_UNSP_DOC_PORTABLECOLLECTION: i32 = 2;
pub const FPDF_UNSP_DOC_ATTACHMENT: i32 = 3;
pub const FPDF_UNSP_DOC_SECURITY: i32 = 4;
pub const FPDF_UNSP_DOC_SHAREDREVIEW: i32 = 5;
pub const FPDF_UNSP_DOC_SHAREDFORM_ACROBAT: i32 = 6;
pub const FPDF_UNSP_DOC_SHAREDFORM_FILESYSTEM: i32 = 7;
pub const FPDF_UNSP_DOC_SHAREDFORM_EMAIL: i32 = 8;
pub const FPDF_UNSP_ANNOT_3DANNOT: i32 = 11;
pub const FPDF_UNSP_ANNOT_MOVIE: i32 = 12;
pub const FPDF_UNSP_ANNOT_SOUND: i32 = 13;
pub const FPDF_UNSP_ANNOT_SCREEN_MEDIA: i32 = 14;
pub const FPDF_UNSP_ANNOT_SCREEN_RICHMEDIA: i32 = 15;
pub const FPDF_UNSP_ANNOT_ATTACHMENT: i32 = 16;
pub const FPDF_UNSP_ANNOT_SIG: i32 = 17;
pub const FPDF_RENDER_READY: i32 = 0;
pub const FPDF_RENDER_TOBECONTINUED: i32 = 1;
pub const FPDF_RENDER_DONE: i32 = 2;
pub const FPDF_RENDER_FAILED: i32 = 3;
pub const FPDF_INCREMENTAL: i32 = 1;
pub const FPDF_NO_INCREMENTAL: i32 = 2;
pub const FPDF_REMOVE_SECURITY: i32 = 3;
pub const FPDF_MATCHCASE: i32 = 1;
pub const FPDF_MATCHWHOLEWORD: i32 = 2;
pub const FPDF_CONSECUTIVE: i32 = 4;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_UNKNOWN: FPDF_TEXT_RENDERMODE = -1;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_FILL: FPDF_TEXT_RENDERMODE = 0;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_STROKE: FPDF_TEXT_RENDERMODE = 1;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_FILL_STROKE: FPDF_TEXT_RENDERMODE = 2;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_INVISIBLE: FPDF_TEXT_RENDERMODE = 3;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_FILL_CLIP: FPDF_TEXT_RENDERMODE = 4;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_STROKE_CLIP: FPDF_TEXT_RENDERMODE = 5;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_FILL_STROKE_CLIP: FPDF_TEXT_RENDERMODE = 6;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_CLIP: FPDF_TEXT_RENDERMODE = 7;
pub const FPDF_TEXT_RENDERMODE_FPDF_TEXTRENDERMODE_LAST: FPDF_TEXT_RENDERMODE = 7;
pub const _FPDF_DUPLEXTYPE__DuplexUndefined: _FPDF_DUPLEXTYPE_ = 0;
pub const _FPDF_DUPLEXTYPE__Simplex: _FPDF_DUPLEXTYPE_ = 1;
pub const _FPDF_DUPLEXTYPE__DuplexFlipShortEdge: _FPDF_DUPLEXTYPE_ = 2;
pub const _FPDF_DUPLEXTYPE__DuplexFlipLongEdge: _FPDF_DUPLEXTYPE_ = 3;
pub const FPDF_RENDERER_TYPE_FPDF_RENDERERTYPE_AGG: FPDF_RENDERER_TYPE = 0;
pub const FPDF_RENDERER_TYPE_FPDF_RENDERERTYPE_SKIA: FPDF_RENDERER_TYPE = 1;
pub const FPDFANNOT_COLORTYPE_FPDFANNOT_COLORTYPE_Color: FPDFANNOT_COLORTYPE = 0;
pub const FPDFANNOT_COLORTYPE_FPDFANNOT_COLORTYPE_InteriorColor: FPDFANNOT_COLORTYPE = 1;
pub const FPDF_FILEIDTYPE_FILEIDTYPE_PERMANENT: FPDF_FILEIDTYPE = 0;
pub const FPDF_FILEIDTYPE_FILEIDTYPE_CHANGING: FPDF_FILEIDTYPE = 1;
